export default {
	solid: [
		'faSearch',
		'faExternalLink',
		'faAngleDown',
		'faFaceSmile',
		'faHatWizard',
		'faDiceD6',
		'faDiceD20',
		'faDragon',
		'faClose',
		'faSpinner',
		'faAnglesLeft',
		'faAngleLeft',
		'faAngleRight',
		'faAnglesRight',
		'faCircleExclamation',
		'faCopyright',
		'faMagnifyingGlassPlus',
	],
	regular: ['faCircleQuestion'],
	brands: ['faTwitter', 'faFacebook', 'faGithub'],
}
